name: myenv
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - graphviz
  - pip:
      - pm4py
      - google-genai
      - anthropic
      - rustxes
      - setuptools
      - streamlit
      - requests
